### ISSUE TITLE
Send broadcast instead of multicast traffic with -M option

### ISSUE THREAD

**Issue by jokajak** [jedisct1/UCarp#12]
All that --nomcast appears to do from looking at the source code (carp.c 257-263) is to use the broadcast IP address. "tcpdump -n broadcast" shows multicast packets being broadcast, but when I use the filter "broadcast and no multicast" it all vanishes.

**Comment by petiepooo** [comment]
To be precise, I believe you mean that it uses the broadcast MAC, not the broadcast IP address.  It still sends it to the multicast IP address.  Use tcpdump's '-e' flag to view the ethernet header and see the change.
