### ISSUE TITLE
Command line option for disabling MAC address spoofing?

### ISSUE THREAD

**Issue by smlz** [jedisct1/UCarp#19]
UCarp spoofs the sending MAC address. See: https://github.com/jedisct1/UCarp/blob/master/src/carp.c#L248-L253

This can lead to problems in some virtualized environments, where packets with spoofed sender MAC addresses are filtered by default. oVirt does this for example: http://lists.ovirt.org/pipermail/users/2013-October/017217.html

What is the rationale behind the spoofed MAC addresses anyway?

I cannot see it in used on the receiving end, other than for logging purpose: https://github.com/jedisct1/UCarp/blob/master/src/carp.c#L418-L423 

Maybe a command line option like `--no-spoofing` could be useful. Would you be interested in including such a feature? I might actually give it a shot ...

**Comment by smlz** [comment]
To answer my own question: \*BSDs (on which CAPR was originally implemented) do CARP in the kernel. Using the same virtual IP **and**  MAC address across multiple hosts, allows a backup firewall/router to take over service from a failing host, without losing any TCP connections. Advertising using the same MAC address just makes the switch send the packets to another port, without the need of updating any APR tables.

The same would be quite hard to implement in user space, so there is not much use of this 'feature'.

**Comment by petiepooo** [comment]
I need this feature myself, or something similar.
Specifically, when running keepalived, I see the source MAC is the NIC's native MAC, and everything works as designed.  However, ucarp uses a multicast source MAC, and I believe that's being filtered, probably by the virtual switch connecting the hosts.
I propose adding an argument that allows switching between the existing MAC (default), the NIC's native MAC, or a MAC specified on the command-line.  I thought I saw another spec where it was still a multicast MAC, but with a 0x01 in one of the octets currently 0x00.

**Comment by dekimsey** [comment]
I ran into this as well. VSphere distributed switches is filtering the traffic because of the spoofed MACs. 

Without being able to disable the behavior, I'm unable to use the program.
