### ISSUE TITLE
Times Failover

### ISSUE THREAD

**Issue by reskiuni** [jedisct1/UCarp#23]
how long default times failover ucarp?
Because I get from my system of 4-5 seconds doing failover. 
and I am looking for reasons why the time is like that

**Comment by petiepooo** [comment]
What are your configured deadratio and advertisement base and skew values?  The defaults give 1-second ads and deadratio of 3, which means three missed ads should cause a switch.  Depending on the time between when the last ad was sent and the active node exits, that could be between 3 and 4 seconds before the standby node misses three ads and starts a switchover.  Add a few milliseconds to bring the VIP up, and your observation of 4-5 seconds is reasonable.

To change that, you'll need to fiddle with the --deadratio, --advbase and --advskew parameters as described in the README file.

**Comment by petiepooo** [comment]
I don't see why not.  Test before putting into production, of course.
