### ISSUE TITLE
Restarting network with ucarp will cause vip never come up

### ISSUE THREAD

**Issue by chenzhiwei** [jedisct1/UCarp#26]
## Situation

This was supposed to be a normal setup: highly-available gateways/firewall with ucarp.

Everything works until I restart my network, then I lost the VIP from the interface.

## The Possible Reason

UCarp does not monitor the interface status and attach the VIP to it(or do a new leader election).

UCarp should do a new leader election when the interface is down, or attach the VIP to the interface when it go up.

## Current solution

We need to manually restart ucarp to do a new leader election.

Here is the command to start ucarp:

```
ucarp --interface=eth0 --srcip=1.2.3.4 --vhid=10 --pass=1234 --addr=1.2.3.10 --upscript=/etc/vip-up.sh --downscript=/etc/vip-down.sh
```

**Comment by kerframil** [comment]
My approach for simulating OpenBSD's preemption feature is twofold:

1. Ensure that all instances are launched with the `--shutdown` option
2. Have the down script issue a USR2 signal to all running instances

However, great care must be taken to ensure that the instance of the down script that first issues the signal does not permit any other instance to issue the signal as a direct consequence. Below is a sample down script that relies on the use of the flock command from util-linux.

```sh
#!/usr/bin/bash

# Delete address
ip addr del "$2"/"$3" dev "$1"

exec 9>/tmp/vip-down.lock
if ! flock -n 9; then
    # Another instance holds the lock
   exit 0
fi

# Signal other instances to hand over
pkill -USR2 ucarp
sleep 1
```
