### ISSUE TITLE
Documentation on building from source

### ISSUE THREAD

**Issue by gmjosack** [jedisct1/UCarp#9]
The non-packaged source that is pulled from Github requires some incantation of autotools that doesn't appear to be documented and that I couldn't quite figure out. I ended up testing a patch against the packaged version that already has configure/make. 

If you could help me get the proper incantation, I'd love to get it documented in either the README or a BUILD file.

Thanks!

**Comment by cornet** [comment]
The following worked for me on Ubuntu 14.01

Install some dependencies (there may be more which I already had)
```shell
apt-get install libtool autoconf
```

Then from within the cloned repo
```shell
libtoolize
gettextize -f

cp po/Makevars.template po/Makevars
autoreconf -i

./configure
make
```

**Comment by petiepooo** [comment]
I love the GIF, @jedisct1!  I'm saving it for appropriate occasions...
Autotools are still mostly magic to me, but I did manage to get Travis CI to actually build things.  The updates are currently in my fork, but after updating some m4/po files, it's been boiled down to just:
<pre>autoreconf --force --install
./configure --disable-dependency-tracking
make check</pre>
I'll leave this open for reference until the updates are in master.
